version: '2'
services:
  herokudemo2-app:
    image: herokudemo2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://herokudemo2-postgresql:5432/herokuDemo2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  herokudemo2-postgresql:
    extends:
      file: postgresql.yml
      service: herokudemo2-postgresql
